/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_csail_uid_NativeLayerForMac */

#ifndef _Included_edu_mit_csail_uid_NativeLayerForMac
#define _Included_edu_mit_csail_uid_NativeLayerForMac
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_mit_csail_uid_NativeLayerForMac_KEY_CMD
#define edu_mit_csail_uid_NativeLayerForMac_KEY_CMD 256L
#undef edu_mit_csail_uid_NativeLayerForMac_KEY_SHIFT
#define edu_mit_csail_uid_NativeLayerForMac_KEY_SHIFT 512L
/*
 * Class:     edu_mit_csail_uid_NativeLayerForMac
 * Method:    installGlobalHotkey
 * Signature: (IILedu/mit/csail/uid/SikuliIDE;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_mit_csail_uid_NativeLayerForMac_installGlobalHotkey
  (JNIEnv *, jobject, jint, jint, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
