/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sikuli_ide_NativeLayerForMac */

#ifndef _Included_org_sikuli_ide_NativeLayerForMac
#define _Included_org_sikuli_ide_NativeLayerForMac
#ifdef __cplusplus
extern "C" {
#endif
#undef org_sikuli_ide_NativeLayerForMac_CARBON_MASK_CMD
#define org_sikuli_ide_NativeLayerForMac_CARBON_MASK_CMD 256L
#undef org_sikuli_ide_NativeLayerForMac_CARBON_MASK_SHIFT
#define org_sikuli_ide_NativeLayerForMac_CARBON_MASK_SHIFT 512L
#undef org_sikuli_ide_NativeLayerForMac_CARBON_MASK_OPT
#define org_sikuli_ide_NativeLayerForMac_CARBON_MASK_OPT 2048L
#undef org_sikuli_ide_NativeLayerForMac_CARBON_MASK_CTRL
#define org_sikuli_ide_NativeLayerForMac_CARBON_MASK_CTRL 4096L
/*
 * Class:     org_sikuli_ide_NativeLayerForMac
 * Method:    installGlobalHotkey
 * Signature: (IILorg/sikuli/ide/SikuliIDE;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_sikuli_ide_NativeLayerForMac_installGlobalHotkey
  (JNIEnv *, jobject, jint, jint, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
