#!/bin/bash

sikulidir=`dirname $0`
cd $sikulidir
if [ -d sikuli-script/build ]; then
    pushd sikuli-script/build
    make clean
    popd
fi
if [ -d sikuli-ide/build ]; then
    pushd sikuli-ide/build
    make clean
    popd
fi
mkdir -p sikuli-script/build
pushd sikuli-script/build
cmake ..
make
popd
mkdir -p sikuli-ide/build
pushd sikuli-ide/build
cmake ..
make package
popd
