/*
 * Copyright 2010-2011, Sikuli.org
 * Released under the MIT License.
 *
 */
package org.sikuli.script;

import java.awt.event.KeyEvent;

public class Key {
   public static final char ENTER       = '\n';
   public static final char BACKSPACE   = '\b';
   public static final char TAB         = '\t';
   public static final char ESC         = '\u001b';
   public static final char UP          = '\ue000';
   public static final char RIGHT       = '\ue001';
   public static final char DOWN        = '\ue002';
   public static final char LEFT        = '\ue003';
   public static final char PAGE_UP     = '\ue004';
   public static final char PAGE_DOWN   = '\ue005';
   public static final char DELETE      = '\ue006';
   public static final char END         = '\ue007';
   public static final char HOME        = '\ue008';
   public static final char INSERT      = '\ue009';
   public static final char F1          = '\ue011';
   public static final char F2          = '\ue012';
   public static final char F3          = '\ue013';
   public static final char F4          = '\ue014';
   public static final char F5          = '\ue015';
   public static final char F6          = '\ue016';
   public static final char F7          = '\ue017';
   public static final char F8          = '\ue018';
   public static final char F9          = '\ue019';
   public static final char F10         = '\ue01A';
   public static final char F11         = '\ue01B';
   public static final char F12         = '\ue01C';
   public static final char F13         = '\ue01D';
   public static final char F14         = '\ue01E';
   public static final char F15         = '\ue01F';
   public static final char SHIFT       = '\ue020';
   public static final char CTRL        = '\ue021';
   public static final char ALT         = '\ue022';
   public static final char META        = '\ue023';
   public static final char CMD         = '\ue023';
   public static final char WIN         = '\ue023';
   public static final char PRINTSCREEN = '\ue024';
   public static final char SCROLL_LOCK = '\ue025';
   public static final char PAUSE       = '\ue026';
   public static final char CAPS_LOCK   = '\ue027';
   public static final char NUM0        = '\ue030';
   public static final char NUM1        = '\ue031';
   public static final char NUM2        = '\ue032';
   public static final char NUM3        = '\ue033';
   public static final char NUM4        = '\ue034';
   public static final char NUM5        = '\ue035';
   public static final char NUM6        = '\ue036';
   public static final char NUM7        = '\ue037';
   public static final char NUM8        = '\ue038';
   public static final char NUM9        = '\ue039';
   public static final char SEPARATOR   = '\ue03A';
   public static final char NUM_LOCK    = '\ue03B';
   public static final char ADD         = '\ue03C';
   public static final char MINUS       = '\ue03D';
   public static final char MULTIPLY    = '\ue03E';
   public static final char DIVIDE      = '\ue03F';

   /**
    *  Convert Sikuli Key to Java virtual key code
    */ 
   public static int[] toJavaKeyCode(char key){
      switch (key) {
         case 'a': return new int[] {KeyEvent.VK_A};
         case 'b': return new int[] {KeyEvent.VK_B};
         case 'c': return new int[] {KeyEvent.VK_C};
         case 'd': return new int[] {KeyEvent.VK_D};
         case 'e': return new int[] {KeyEvent.VK_E};
         case 'f': return new int[] {KeyEvent.VK_F};
         case 'g': return new int[] {KeyEvent.VK_G};
         case 'h': return new int[] {KeyEvent.VK_H};
         case 'i': return new int[] {KeyEvent.VK_I};
         case 'j': return new int[] {KeyEvent.VK_J};
         case 'k': return new int[] {KeyEvent.VK_K};
         case 'l': return new int[] {KeyEvent.VK_L};
         case 'm': return new int[] {KeyEvent.VK_M};
         case 'n': return new int[] {KeyEvent.VK_N};
         case 'o': return new int[] {KeyEvent.VK_O};
         case 'p': return new int[] {KeyEvent.VK_P};
         case 'q': return new int[] {KeyEvent.VK_Q};
         case 'r': return new int[] {KeyEvent.VK_R};
         case 's': return new int[] {KeyEvent.VK_S};
         case 't': return new int[] {KeyEvent.VK_T};
         case 'u': return new int[] {KeyEvent.VK_U};
         case 'v': return new int[] {KeyEvent.VK_V};
         case 'w': return new int[] {KeyEvent.VK_W};
         case 'x': return new int[] {KeyEvent.VK_X};
         case 'y': return new int[] {KeyEvent.VK_Y};
         case 'z': return new int[] {KeyEvent.VK_Z};
         case 'A': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_A};
         case 'B': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_B};
         case 'C': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_C};
         case 'D': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_D};
         case 'E': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_E};
         case 'F': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_F};
         case 'G': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_G};
         case 'H': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_H};
         case 'I': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_I};
         case 'J': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_J};
         case 'K': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_K};
         case 'L': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_L};
         case 'M': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_M};
         case 'N': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_N};
         case 'O': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_O};
         case 'P': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_P};
         case 'Q': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_Q};
         case 'R': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_R};
         case 'S': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_S};
         case 'T': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_T};
         case 'U': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_U};
         case 'V': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_V};
         case 'W': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_W};
         case 'X': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_X};
         case 'Y': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_Y};
         case 'Z': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_Z};
         case '`': return new int[] {KeyEvent.VK_BACK_QUOTE};
         case '0': return new int[] {KeyEvent.VK_0};
         case '1': return new int[] {KeyEvent.VK_1};
         case '2': return new int[] {KeyEvent.VK_2};
         case '3': return new int[] {KeyEvent.VK_3};
         case '4': return new int[] {KeyEvent.VK_4};
         case '5': return new int[] {KeyEvent.VK_5};
         case '6': return new int[] {KeyEvent.VK_6};
         case '7': return new int[] {KeyEvent.VK_7};
         case '8': return new int[] {KeyEvent.VK_8};
         case '9': return new int[] {KeyEvent.VK_9};
         case '-': return new int[] {KeyEvent.VK_MINUS};
         case '=': return new int[] {KeyEvent.VK_EQUALS};
         case '~': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_BACK_QUOTE};
         case '!': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_1};
         case '@': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_2};
         case '#': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_3};
         case '$': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_4};
         case '%': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_5};
         case '^': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_6};
         case '&': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_7};
         case '*': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_8};
         case '(': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_9};
         case ')': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_0};
         case '_': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_MINUS};
         case '+': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_EQUALS};
         case '\b':return new int[] {KeyEvent.VK_BACK_SPACE};
         case '\t':return new int[] {KeyEvent.VK_TAB};
         case '\r':return new int[] {KeyEvent.VK_ENTER};
         case '\n':return new int[] {KeyEvent.VK_ENTER};
         case '[': return new int[] {KeyEvent.VK_OPEN_BRACKET};
         case ']': return new int[] {KeyEvent.VK_CLOSE_BRACKET};
         case '\\':return new int[] {KeyEvent.VK_BACK_SLASH};
         case '{': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_OPEN_BRACKET};
         case '}': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_CLOSE_BRACKET};
         case '|': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_BACK_SLASH};
         case ';': return new int[] {KeyEvent.VK_SEMICOLON};
         case ':': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_SEMICOLON};
         case '\'':return new int[] {KeyEvent.VK_QUOTE};
         case '"': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_QUOTE};
         case ',': return new int[] {KeyEvent.VK_COMMA};
         case '<': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_COMMA};
         case '.': return new int[] {KeyEvent.VK_PERIOD};
         case '>': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_PERIOD};
         case '/': return new int[] {KeyEvent.VK_SLASH};
         case '?': return new int[] {KeyEvent.VK_SHIFT, KeyEvent.VK_SLASH};
         case ' ': return new int[] {KeyEvent.VK_SPACE};
         case Key.ESC        : return new int[] {KeyEvent.VK_ESCAPE};
         case Key.UP         : return new int[] {KeyEvent.VK_UP};
         case Key.RIGHT      : return new int[] {KeyEvent.VK_RIGHT};
         case Key.DOWN       : return new int[] {KeyEvent.VK_DOWN};
         case Key.LEFT       : return new int[] {KeyEvent.VK_LEFT};
         case Key.PAGE_UP    : return new int[] {KeyEvent.VK_PAGE_UP};
         case Key.PAGE_DOWN  : return new int[] {KeyEvent.VK_PAGE_DOWN};
         case Key.DELETE     : return new int[] {KeyEvent.VK_DELETE};
         case Key.END        : return new int[] {KeyEvent.VK_END};
         case Key.HOME       : return new int[] {KeyEvent.VK_HOME};
         case Key.INSERT     : return new int[] {KeyEvent.VK_INSERT};
         case Key.F1         : return new int[] {KeyEvent.VK_F1};
         case Key.F2         : return new int[] {KeyEvent.VK_F2};
         case Key.F3         : return new int[] {KeyEvent.VK_F3};
         case Key.F4         : return new int[] {KeyEvent.VK_F4};
         case Key.F5         : return new int[] {KeyEvent.VK_F5};
         case Key.F6         : return new int[] {KeyEvent.VK_F6};
         case Key.F7         : return new int[] {KeyEvent.VK_F7};
         case Key.F8         : return new int[] {KeyEvent.VK_F8};
         case Key.F9         : return new int[] {KeyEvent.VK_F9};
         case Key.F10        : return new int[] {KeyEvent.VK_F10};
         case Key.F11        : return new int[] {KeyEvent.VK_F11};
         case Key.F12        : return new int[] {KeyEvent.VK_F12};
         case Key.F13        : return new int[] {KeyEvent.VK_F13};
         case Key.F14        : return new int[] {KeyEvent.VK_F14};
         case Key.F15        : return new int[] {KeyEvent.VK_F15};
         case Key.SHIFT      : return new int[] {KeyEvent.VK_SHIFT};
         case Key.CTRL       : return new int[] {KeyEvent.VK_CONTROL};
         case Key.ALT        : return new int[] {KeyEvent.VK_ALT};
         case Key.META       : return new int[] {KeyEvent.VK_META};
         case Key.PRINTSCREEN: return new int[] {KeyEvent.VK_PRINTSCREEN};
         case Key.SCROLL_LOCK: return new int[] {KeyEvent.VK_SCROLL_LOCK};
         case Key.PAUSE      : return new int[] {KeyEvent.VK_PAUSE};
         case Key.CAPS_LOCK  : return new int[] {KeyEvent.VK_CAPS_LOCK};
         case Key.NUM0       : return new int[] {KeyEvent.VK_NUMPAD0};
         case Key.NUM1       : return new int[] {KeyEvent.VK_NUMPAD1};
         case Key.NUM2       : return new int[] {KeyEvent.VK_NUMPAD2};
         case Key.NUM3       : return new int[] {KeyEvent.VK_NUMPAD3};
         case Key.NUM4       : return new int[] {KeyEvent.VK_NUMPAD4};
         case Key.NUM5       : return new int[] {KeyEvent.VK_NUMPAD5};
         case Key.NUM6       : return new int[] {KeyEvent.VK_NUMPAD6};
         case Key.NUM7       : return new int[] {KeyEvent.VK_NUMPAD7};
         case Key.NUM8       : return new int[] {KeyEvent.VK_NUMPAD8};
         case Key.NUM9       : return new int[] {KeyEvent.VK_NUMPAD9};
         case Key.SEPARATOR  : return new int[] {KeyEvent.VK_SEPARATOR};
         case Key.NUM_LOCK   : return new int[] {KeyEvent.VK_NUM_LOCK};
         case Key.ADD        : return new int[] {KeyEvent.VK_ADD};
         case Key.MINUS      : return new int[] {KeyEvent.VK_MINUS};
         case Key.MULTIPLY   : return new int[] {KeyEvent.VK_MULTIPLY};
         case Key.DIVIDE     : return new int[] {KeyEvent.VK_DIVIDE};
         default:
            throw new IllegalArgumentException("Cannot convert character " + key);
      }
   }
}
