PACKAGE = edu.mit.csail.uid

SOURCE  = \
   CapturePrompt.java \
   Clipboard.java \
   Debug.java \
   DummyOSUtil.java \
   Finder.java \
   FindFailed.java \
   KeyCodeConverter.java \
   LinuxUtil.java \
   MacUtil.java \
   Match.java \
   Matches.java \
   Observer.java \
   OSUtil.java \
   OverlayWindow.java \
   Pattern.java \
   ScreenMatchProxy.java \
   ScriptRunner.java \
   SikuliScript.java \
   Similar.java \
   Subject.java \
   SubregionJ.java \
   TestScreenMatchProxy.java \
   TestSikuliScript.java \
   VDictProxy.java \
   Win32Util.java

JNI_SOURCE = VDictProxy.java ScreenMatchProxy.java Finder.java 

include $(DEV_ROOT)/Makefile.common
