PACKAGE = edu.mit.csail.uid

SOURCE  = \
AppearEvent.java \
CapturePrompt.java \
ChangeEvent.java \
Clipboard.java \
Debug.java \
DummyOSUtil.java \
Env.java \
EventManager.java \
FindFailed.java \
Finder.java \
KeyCodeConverter.java \
LinuxUtil.java \
Location.java \
MacUtil.java \
Match.java \
OSUtil.java \
Observer.java \
OpenCV.java \
OverlayWindow.java \
Pattern.java \
Region.java \
Screen.java \
ScreenImage.java \
ScriptRunner.java \
Settings.java \
SikuliEvent.java \
SikuliEventAdapter.java \
SikuliEventObserver.java \
SikuliScript.java \
Subject.java \
VDictProxy.java \
VanishEvent.java \
Win32Util.java 

JNI_SOURCE = VDictProxy.java ScreenMatchProxy.java Finder.java EventManager.java

include $(DEV_ROOT)/Makefile.common
