/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_csail_uid_MacUtil */

#ifndef _Included_edu_mit_csail_uid_MacUtil
#define _Included_edu_mit_csail_uid_MacUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_csail_uid_MacUtil
 * Method:    bringWindowToFront
 * Signature: (Ljava/awt/Window;)V
 */
JNIEXPORT void JNICALL Java_edu_mit_csail_uid_MacUtil_bringWindowToFront
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
