/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_csail_uid_ScreenMatchProxy */

#ifndef _Included_edu_mit_csail_uid_ScreenMatchProxy
#define _Included_edu_mit_csail_uid_ScreenMatchProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_csail_uid_ScreenMatchProxy
 * Method:    screenMatchByOCR
 * Signature: (Ljava/lang/String;Ljava/lang/String;DI)[Ledu/mit/csail/uid/Match;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_mit_csail_uid_ScreenMatchProxy_screenMatchByOCR
  (JNIEnv *, jobject, jstring, jstring, jdouble, jint);

/*
 * Class:     edu_mit_csail_uid_ScreenMatchProxy
 * Method:    screenMatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;DI)[Ledu/mit/csail/uid/Match;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_mit_csail_uid_ScreenMatchProxy_screenMatch
  (JNIEnv *, jobject, jstring, jstring, jdouble, jint);

/*
 * Class:     edu_mit_csail_uid_ScreenMatchProxy
 * Method:    screenDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ledu/mit/csail/uid/Match;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_mit_csail_uid_ScreenMatchProxy_screenDiff
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
