/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_csail_uid_Win32Util */

#ifndef _Included_edu_mit_csail_uid_Win32Util
#define _Included_edu_mit_csail_uid_Win32Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_csail_uid_Win32Util
 * Method:    switchApp
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_csail_uid_Win32Util_switchApp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_mit_csail_uid_Win32Util
 * Method:    openApp
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_csail_uid_Win32Util_openApp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_mit_csail_uid_Win32Util
 * Method:    closeApp
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_csail_uid_Win32Util_closeApp
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
