/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_csail_uid_ScreenMatchProxy_Match */

#ifndef _Included_edu_mit_csail_uid_ScreenMatchProxy_Match
#define _Included_edu_mit_csail_uid_ScreenMatchProxy_Match
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
