DEV_ROOT=../../..
include $(DEV_ROOT)/Makefile.common
include Makefile.common

LDFLAGS+=-ltiff 

OBJS = EventManagerProxy.o FinderProxy.o finder.o event-manager.o TimingBlock.o pyramid-template-matcher.o
DYN_LIB = $(JNI_TARGET_DIR)/libScreenMatchProxy.$(DYN_LIB_POSTFIX) 

default $(DYN_LIB): $(OBJS) $(JNI_TARGET_DIR)
	$(CXX) $(OBJS) -o $(DYN_LIB) $(LDFLAGS) 
