DEV_ROOT=../../..
include $(DEV_ROOT)/Makefile.common
include Makefile.common

OBJS = VDictProxy.o
DYN_LIB = $(JNI_TARGET_DIR)/libVDictProxy.$(DYN_LIB_POSTFIX)

default $(DYN_LIB): $(OBJS)
	$(CXX) $(OBJS) -o $(DYN_LIB) $(LDFLAGS) 

