/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sikuli_script_MacUtil */

#ifndef _Included_org_sikuli_script_MacUtil
#define _Included_org_sikuli_script_MacUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sikuli_script_MacUtil
 * Method:    bringWindowToFront
 * Signature: (Ljavax/swing/JWindow;Z)V
 */
JNIEXPORT void JNICALL Java_org_sikuli_script_MacUtil_bringWindowToFront
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_sikuli_script_MacUtil
 * Method:    _openApp
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sikuli_script_MacUtil__1openApp
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_sikuli_script_MacUtil
 * Method:    getPID
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_sikuli_script_MacUtil_getPID
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_sikuli_script_MacUtil
 * Method:    getRegion
 * Signature: (JI)Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_org_sikuli_script_MacUtil_getRegion
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_sikuli_script_MacUtil
 * Method:    getFocusedRegion
 * Signature: ()Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_org_sikuli_script_MacUtil_getFocusedRegion
  (JNIEnv *, jclass);

/*
 * Class:     org_sikuli_script_MacUtil
 * Method:    isAxEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_sikuli_script_MacUtil_isAxEnabled
  (JNIEnv *, jclass);

/*
 * Class:     org_sikuli_script_MacUtil
 * Method:    openAxSetting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_sikuli_script_MacUtil_openAxSetting
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
