/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sikuli_script_EventManager */

#ifndef _Included_org_sikuli_script_EventManager
#define _Included_org_sikuli_script_EventManager
#ifdef __cplusplus
extern "C" {
#endif
#undef org_sikuli_script_EventManager_APPEAR
#define org_sikuli_script_EventManager_APPEAR 0L
#undef org_sikuli_script_EventManager_VANISH
#define org_sikuli_script_EventManager_VANISH 1L
#undef org_sikuli_script_EventManager_CHANGE
#define org_sikuli_script_EventManager_CHANGE 2L
/*
 * Class:     org_sikuli_script_EventManager
 * Method:    createEventManager
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sikuli_script_EventManager_createEventManager
  (JNIEnv *, jobject);

/*
 * Class:     org_sikuli_script_EventManager
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sikuli_script_EventManager_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_sikuli_script_EventManager
 * Method:    addObserver
 * Signature: (JILjava/lang/String;FIIIII)V
 */
JNIEXPORT void JNICALL Java_org_sikuli_script_EventManager_addObserver
  (JNIEnv *, jobject, jlong, jint, jstring, jfloat, jint, jint, jint, jint, jint);

/*
 * Class:     org_sikuli_script_EventManager
 * Method:    _update
 * Signature: (J[BII)[Lorg/sikuli/script/SikuliEvent;
 */
JNIEXPORT jobjectArray JNICALL Java_org_sikuli_script_EventManager__1update
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
