/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sikuli_script_Win32Util */

#ifndef _Included_org_sikuli_script_Win32Util
#define _Included_org_sikuli_script_Win32Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sikuli_script_Win32Util
 * Method:    switchApp
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_sikuli_script_Win32Util_switchApp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_sikuli_script_Win32Util
 * Method:    openApp
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_sikuli_script_Win32Util_openApp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_sikuli_script_Win32Util
 * Method:    closeApp
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_sikuli_script_Win32Util_closeApp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_sikuli_script_Win32Util
 * Method:    bringWindowToFront
 * Signature: (Ljavax/swing/JWindow;Z)V
 */
JNIEXPORT void JNICALL Java_org_sikuli_script_Win32Util_bringWindowToFront
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_sikuli_script_Win32Util
 * Method:    getPID
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_sikuli_script_Win32Util_getPID
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_sikuli_script_Win32Util
 * Method:    getRegion
 * Signature: (JI)Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_org_sikuli_script_Win32Util_getRegion
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_sikuli_script_Win32Util
 * Method:    getFocusedRegion
 * Signature: ()Ljava/awt/Rectangle;
 */
JNIEXPORT jobject JNICALL Java_org_sikuli_script_Win32Util_getFocusedRegion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
