/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sikuli_script_VNCNative */

#ifndef _Included_org_sikuli_script_VNCNative
#define _Included_org_sikuli_script_VNCNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sikuli_script_VNCNative
 * Method:    rfbGetClient
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_org_sikuli_script_VNCNative_rfbGetClient
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_sikuli_script_VNCNative
 * Method:    rfbInitClient
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_sikuli_script_VNCNative_rfbInitClient
  (JNIEnv *, jclass, jlong, jobjectArray,jstring);

/*
 * Class:     org_sikuli_script_VNCNative
 * Method:    WaitForMessage
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_sikuli_script_VNCNative_WaitForMessage
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_sikuli_script_VNCNative
 * Method:    HandleRFBServerMessage
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sikuli_script_VNCNative_HandleRFBServerMessage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sikuli_script_VNCNative
 * Method:    CopyScreenToData
 * Signature: (J[B)Z
 */
JNIEXPORT void JNICALL Java_org_sikuli_script_VNCNative_CopyScreenToData
  (JNIEnv *, jclass, jlong, jintArray,jint,jint,jint,jint);

/*
 * Class:     org_sikuli_script_VNCNative
 * Method:    GetWidth
 * Signature: (J)Z
 */
JNIEXPORT jint JNICALL Java_org_sikuli_script_VNCNative_GetWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sikuli_script_VNCNative
 * Method:    GetHeight
 * Signature: (J)Z
 */
JNIEXPORT jint JNICALL Java_org_sikuli_script_VNCNative_GetHeight
  (JNIEnv *, jclass, jlong);


/*
 * Class:     org_sikuli_script_VNCNative
 * Method:    SendPointerEvent
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sikuli_script_VNCNative_SendPointerEvent
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_sikuli_script_VNCNative
 * Method:    SendKeyEvent
 * Signature: (JIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sikuli_script_VNCNative_SendKeyEvent
  (JNIEnv *, jclass, jlong, jint, jboolean);



#ifdef __cplusplus
}
#endif
#endif
